### ISSUE TITLE
No icon color in default mode

### ISSUE THREAD

**Issue by AlainRnet** [PhocaCz/PhocaDesktopSystemPlugin#1]
https://github.com/PhocaCz/PhocaDesktopSystemPlugin/blob/37b09ae2343860fc31547e29cbaa45e4b90d391a/media/css/default.css#L93

Because you have set !important, the icon isn't visible in default mode.
It is necessary to add !important after the color code in the json code to see the icon.

A question : how is it possible to set the link open in a new window ?

**Comment by PhocaCz** [comment]
Hi, thank you for the info, will be fixed in next version - for now just comment it or use the desktop.css

link in new window: No, for now, there is no such option. Added to feature request list:
https://github.com/PhocaCz/PhocaDesktopSystemPlugin/issues/2

Jan

**Comment by PhocaCz** [comment]
Hi, try to test this Beta:

https://github.com/PhocaCz/PhocaDesktopSystemPlugin/releases/download/4.0.5Beta/plg_system_phocadesktop_v4.0.5Beta.zip

1) default.css - should be OK now
2) Added new parameter to JSON: linkattribute:
Usage:
"linkattribute":"target=\"blank\"",

Please test and let me know

**Comment by AlainRnet** [comment]
Yes, everything are all right !

**Comment by PhocaCz** [comment]
Great to hear it.
