### ISSUE TITLE
[Feature Request] Add linkattribute parameter to JSON

### ISSUE THREAD

**Issue by PhocaCz** [PhocaCz/PhocaDesktopSystemPlugin#2]
Add linkattribute parameter to JSON

example: 
```
"linkattribute":"target=\"blank\"",
```

**Comment by PhocaCz** [comment]
See: https://github.com/PhocaCz/PhocaDesktopSystemPlugin/releases/download/4.0.5Beta/plg_system_phocadesktop_v4.0.5Beta.zip

**Comment by AlainRnet** [comment]
Works fine !
Also writed "linkattribute":"target='blank'",
Thank you very very much

**Comment by PhocaCz** [comment]
Great to hear it
